---
- name: demo play book for test
  hosts: all
  become: true
  tasks:


    - name: install git
      apt:
        name: git
        update_cache: true
        state: present

    - name: git
      service:
        state: restarted
