---
# handlers file for role1
#
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart tomcat
  systemd:
     name: tomcat
     state: restarted
     enabled: yes
# handlers file for tomcat
